-- Just renamed previous table for now
-- rename table camdf.parature_contact to parature_contact_old;

-- select distinct customer_custom_field_name, customer_custom_field_type from camdf.parature_contact_custom_prestg with ur;


DROP TABLE "CAMDF"."PARATURE_CONTACT";

CREATE TABLE "CAMDF"."PARATURE_CONTACT" (
   "CUSTOMER_ID" BIGINT NOT NULL,
   "EMAIL" VARGRAPHIC(128) NOT NULL, 
   "FIRST_NAME" VARGRAPHIC(128), 
   "LAST_NAME" VARGRAPHIC(128), 
   "IBM_UID" VARCHAR(35), 
   "ROLE" VARCHAR(40), 
   "STATUS" VARCHAR(20), 
   "PHONE_NUMBER" VARCHAR(50), 
   "ALTERNATE_PHONE_NUMBER" VARCHAR(40), 
   "CONTACT_COUNTRY" VARCHAR(256), 
   "PREFERRED_LANGUAGE" VARCHAR(64), 
   "TIMEZONE" VARCHAR(64), 
   "ACCOUNT_ID" BIGINT,   
   "DATE_CREATED" TIMESTAMP, 
   "DATE_MODIFIED" TIMESTAMP, 
   "DATE_LAST_VISITED" TIMESTAMP, 
   "IBM_UID_FROM_EMAIL" VARCHAR(35), 
   "SOURCE_ID" VARCHAR(40), 
   "CREATE_USER" VARGRAPHIC(127), 
   "CREATE_DATETIME" TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP, 
   "UPDATE_USER" VARGRAPHIC(127), 
   "UPDATE_DATETIME" TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP, 
   "CREATE_SRC_APPL" VARCHAR(127) NOT NULL DEFAULT 'INTSYS', 
   "UPDATE_SRC_APPL" VARCHAR(127) NOT NULL DEFAULT 'INTSYS', 
   "MIGRATION_ENABLED" SMALLINT, 
   "MIGRATION_DATETIME" TIMESTAMP,
   "MIGRATION_NOTES" VARCHAR(1024)
)
DATA CAPTURE NONE 
COMPRESS NO;

CREATE INDEX "CAMDF"."PARATURE_CONTACT_PK"
	ON "CAMDF"."PARATURE_CONTACT"
	("CUSTOMER_ID"		ASC)
	MINPCTUSED 0
	ALLOW REVERSE SCANS
	PAGE SPLIT SYMMETRIC
	COLLECT SAMPLED DETAILED STATISTICS
	COMPRESS NO;


ALTER TABLE "CAMDF"."PARATURE_CONTACT" ADD CONSTRAINT "PARATURE_CONTACT_PK" PRIMARY KEY
	("CUSTOMER_ID");
	
DROP TRIGGER "CAMDF"."T_IB_PARATURE_CONTACT";	
CREATE TRIGGER "CAMDF"."T_IB_PARATURE_CONTACT" 
	BEFORE INSERT ON "CAMDF"."PARATURE_CONTACT"
	REFERENCING  NEW AS N
	FOR EACH ROW
	NOT SECURED
BEGIN ATOMIC
   SET N.CREATE_DATETIME = CURRENT TIMESTAMP;--
   SET N.UPDATE_DATETIME = CURRENT TIMESTAMP;--
   SET N.UPDATE_USER = N.CREATE_USER;--
   IF (N.CREATE_USER IS NULL OR RTRIM(N.CREATE_USER) = '') THEN
      SET N.CREATE_USER = USER;--
      SET N.UPDATE_USER = USER;--
   END IF;--
END;

DROP TRIGGER "CAMDF"."T_UB_PARATURE_CONTACT"; 
CREATE TRIGGER "CAMDF"."T_UB_PARATURE_CONTACT" 
	BEFORE UPDATE ON "CAMDF"."PARATURE_CONTACT"
	REFERENCING  NEW AS N
	FOR EACH ROW
	NOT SECURED
begin atomic
  set n.update_datetime = current timestamp;--
  if nvl(rtrim(n.update_user), '') = '' then
    set n.update_user = user;  --
  end if; --
  if nvl(rtrim(n.update_src_appl), '') = '' then
    set n.update_src_appl = 'INTSYS';  --
  end if; --
end;
