echo "Loading data to CAMDF.PARATURE_ACCOUNT..."
#gzip -d CAMDF.PARATURE_ACCOUNT.IXF.gz

db2 connect to etl2sf
db2 "IMPORT FROM CAMDF.PARATURE_ACCOUNT.IXF OF IXF COMMITCOUNT 50000 
INSERT INTO CAMDF.PARATURE_ACCOUNT (ACCOUNT_ID, ACCOUNT_NAME, IBM_CUST_NUM, TYPE, CUSTOMER_HUB_ID, CUSTOMER_HUB_KEY,CLIENT_STREET, CLIENT_CITY, CLIENT_STATE_REGION, CLIENT_POSTAL_CODE, CLIENT_COUNTRY,PREMIUM_ACCOUNT, ALERT_INDICATOR, ALERT_COMMENTS, DATE_CREATED, DATE_LAST_MODIFIED)" >> IMPORT_PARATURE_ACCOUNT.ERR

#gzip CAMDF.PARATURE_CONTACT_PRESTG.IXF
