-- Added indexes to help with updating ibm_uid
CREATE INDEX "CAMDF"."SSM_REGISTERED_USERS_TMP1"
	ON "CAMDF"."SSM_REGISTERED_USERS_TMP"
	("EMAIL_ADDRESS"		ASC)
	MINPCTUSED 0
	ALLOW REVERSE SCANS
	PAGE SPLIT SYMMETRIC
	COLLECT SAMPLED DETAILED STATISTICS
	COMPRESS NO;


CREATE INDEX "CAMDF"."PARATURE_CONTACT1"
	ON "CAMDF"."PARATURE_CONTACT"
	("EMAIL"		ASC)
	MINPCTUSED 0
	ALLOW REVERSE SCANS
	PAGE SPLIT SYMMETRIC
	COLLECT SAMPLED DETAILED STATISTICS
	COMPRESS NO;
